name: HACS Validation

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  hacs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: Validate with HACS Action
        uses: hacs/action@main
        with:
          category: "integration"
