name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v5

      # Validate standalone integration structure with Home Assistant hassfest action
      - name: Validate with hassfest
        uses: home-assistant/actions/hassfest@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --no-cache-dir -r requirements_test.txt

      - name: Install system libraries
        run: |
          sudo apt-get update
          sudo apt-get install -y libturbojpeg

      - name: Lint with ruff
        run: |
          ruff check custom_components/wiim --line-length 120

      - name: Lint with flake8
        run: |
          flake8 custom_components/wiim --max-line-length=120 --extend-ignore=E203,W503

      - name: Type check with mypy (strict)
        run: |
          mypy --strict custom_components/wiim

      - name: Test with pytest
        run: |
          pytest tests/ --cov=custom_components/wiim --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
