name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  DEFAULT_PYTHON: "3.13"

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest
    timeout-minutes: 15
    strategy:
      matrix:
        python-version: ["3.13"]
    steps:
      - name: Check out code from GitHub
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements_test.txt

      - name: Lint with flake8
        run: |
          flake8 custom_components/wiim --max-line-length=120 --extend-ignore=E203,W503

      - name: Test with pytest
        run: |
          pytest tests/ --cov=custom_components/wiim --cov-report=xml

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
